name = "Inherit"
uuid = "341b8389-5eed-42ab-a01e-622c6bedf032"
authors = ["mind6 <kirbyzhang@live.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
