name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  id-token: write   # needed for OIDC uploads

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      # (Optional but nice) explicit cache with a stable key
      - name: Cache Julia depot
        uses: actions/cache@v4
        with:
          path: ~/.julia
          key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1  # writes ./lcov.info

      - name: Sanity check coverage file
        run: ls -l lcov.info && head -n 20 lcov.info

      - name: Upload to Codecov (OIDC)
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true          # prefer OIDC over tokens
          files: lcov.info
          flags: unittests
          verbose: true
          fail_ci_if_error: true
